package edu.poly.common;

public enum PageType {
	USER_MANAGEMENT_PAGE, REPORT_MANAGEMENT_PAGE, VIDEO_MANAGEMENT_PAGE, HOME_MANAGEMENT_PAGE, DETAIL_VIDEO_MANAGEMENT_PAGE,
	SHARE_VIDEO_MANAGEMENT_PAGE,
	SITE_HOME_PAGE, SITE_LOGIN_PAGE, SITE_REGISTRATION_PAGE,
	SITE_CHANGE_PASSWORD_PAGE, SITE_EDIT_PROFILE_PAGE, SITE_FORGOT_PASSWORD_PAGE,
	SITE_VIDEO_DETAIL_PAGE, SITE_FAVORITE_PAGE, SITE_SHARE_PAGE, SITE_404_PAGE
}
